from __future__ import annotations

from anonmed.preprocessing.asr.disfluency import (
    CleanedText,
    DisfluencyFilter,
    DisfluencyFilterConfig,
    RemovedSpan,
    remove_disfluencies,
)
from anonmed.preprocessing.asr.contacts import (
    ContactKind,
    ContactNormalizedText,
    ContactNormalizer,
    ContactNormalizerConfig,
    ContactSpan,
    normalize_spoken_contacts,
)
from anonmed.preprocessing.asr.date_birth import (
    DateBirthNormalizedText,
    DateBirthNormalizer,
    DateBirthNormalizerConfig,
    DateBirthSpan,
    normalize_spoken_date_birth,
)
from anonmed.preprocessing.asr.document_numbers import (
    DocumentNumberKind,
    DocumentNumberNormalizedText,
    DocumentNumberNormalizer,
    DocumentNumberNormalizerConfig,
    DocumentNumberReason,
    DocumentNumberRule,
    DocumentNumberSpan,
    build_default_document_number_rules,
    normalize_document_number_runs,
)
from anonmed.preprocessing.asr.number_extractor import (
    IntegerExtractor,
    extract_integers,
    replace_integer_spans,
    replace_spans,
)
from anonmed.preprocessing.asr.pipeline import (
    ASRNormalizationPipeline,
    ASRNormalizationResult,
    run_asr_normalization,
)
from anonmed.preprocessing.asr.punctuation import (
    ProtectedPunctuationSpan,
    PunctuationCleanedText,
    PunctuationFilterConfig,
    PunctuationRemovalConfig,
    PunctuationRemover,
    RemovedPunctuationSpan,
    remove_punctuation,
)
from anonmed.preprocessing.asr.repetition import (
    ASRRepeatDeduplicationConfig,
    ASRRepeatDeduplicationResult,
    ASRRepeatDeduplicator,
    ASRUtterance,
    DeduplicatedASRUtterance,
    RepeatAction,
    RepeatCandidateScore,
    RepeatReason,
    SpeakerMatchPolicy,
    deduplicate_asr_utterances,
)
from anonmed.preprocessing.asr.types import (
    Candidate,
    ExtractorConfig,
    IntegerSpan,
    LexicalMatch,
    NumericToken,
    Token,
)

ASRTextPreprocessingPipeline = ASRNormalizationPipeline
ASRTextPreprocessingResult = ASRNormalizationResult

__all__: list[str] = [
    "ASRNormalizationPipeline",
    "ASRNormalizationResult",
    "ASRRepeatDeduplicationConfig",
    "ASRRepeatDeduplicationResult",
    "ASRRepeatDeduplicator",
    "ASRTextPreprocessingPipeline",
    "ASRTextPreprocessingResult",
    "ASRUtterance",
    "Candidate",
    "CleanedText",
    "ContactKind",
    "ContactNormalizedText",
    "ContactNormalizer",
    "ContactNormalizerConfig",
    "ContactSpan",
    "DateBirthNormalizedText",
    "DateBirthNormalizer",
    "DateBirthNormalizerConfig",
    "DateBirthSpan",
    "DocumentNumberKind",
    "DocumentNumberNormalizedText",
    "DocumentNumberNormalizer",
    "DocumentNumberNormalizerConfig",
    "DocumentNumberReason",
    "DocumentNumberRule",
    "DocumentNumberSpan",
    "DeduplicatedASRUtterance",
    "DisfluencyFilter",
    "DisfluencyFilterConfig",
    "ExtractorConfig",
    "IntegerExtractor",
    "IntegerSpan",
    "LexicalMatch",
    "NumericToken",
    "ProtectedPunctuationSpan",
    "PunctuationCleanedText",
    "PunctuationFilterConfig",
    "PunctuationRemovalConfig",
    "PunctuationRemover",
    "RepeatAction",
    "RepeatCandidateScore",
    "RepeatReason",
    "RemovedPunctuationSpan",
    "RemovedSpan",
    "SpeakerMatchPolicy",
    "Token",
    "build_default_document_number_rules",
    "deduplicate_asr_utterances",
    "extract_integers",
    "normalize_document_number_runs",
    "normalize_spoken_contacts",
    "normalize_spoken_date_birth",
    "remove_disfluencies",
    "remove_punctuation",
    "replace_integer_spans",
    "replace_spans",
    "run_asr_normalization",
]
